export const alertTexts = {
  uploadSuccess: 'Przesłano plik',
  reportGenerationSuccess: 'Wygenerowano raport',
  unkownError: 'Wystąpił nieznany błąd',
  notExcelFileError: 'Niedozwolony format: wymagany .xlsx',
  submitSuccess: 'Zapisano pomyślnie',
  submitError: 'Nie udało się zapisać',
  userChangedSuccess: "Konto użytkownika zmodyfikowane",
  userChangedError: "Nie udało się zmodyfikować konta użytkownika",
  userRemovedSuccess: "Konto użytkownika usunięte",
  userRemovedError: "Nie udało się usunąć konta użytkownika",
  visitDetailsChangedSuccess: 'Wizyta zmodyfikowana',
  visitDetailsChangedError: 'Nie udało się zmodyfikować wizyty',
  visitDetailsAddedSuccess: "Wizyta zapisana",
  visitDetailsAddedError: "Nie udało się zapisać wizyty",
  absenceAddedSuccess: "Nieobecność zapisana",
  absenceAddedError: "Nie udało się zapisać nieobecności",
  absenceChangedSuccess: 'Nieobecność zmodyfikowana',
  absenceChangedError: 'Nie udało się zmodyfikować nieobecności',
  absenceRemovedSuccess: "Nieobecność usunięta",
  absenceRemovedError: "Nie udało się usunąć nieobecności",
  userAddedSuccess: "Utworzono konto użytkownika",
  userAddedError: "Nie udało się utworzyć konta użytkownika",
  loginSuccess: "Zalogowano",
  loginError: "Nie udało się zalogować.</br>Jeśli nie pamiętasz hasła, zwróć się do administratora.",
};
