import {Status} from "shared/enums/visit-details-status.enum";
import {Role} from "shared/enums/roles.enum";

export const generalTexts = {
  absent: 'Nieobecny',
  addVisitForm: 'Formularz dodania wizyty',
  addReportForm: 'Generowanie raportu',
  cancel: 'Anuluj',
  cancelled: 'Wizyta odwołana',
  confirm: 'Kontynuuj',
  date: 'Data',
  fileNotChosen: 'Nie wybrano pliku',
  findCustomer: 'Wybierz beneficjenta',
  findResults: 'Szukaj',
  firstName: 'Imię',
  hour: 'Godzina',
  import: 'Importuj',
  lastName: 'Nazwisko',
  absent_employee: 'Urlop',
  manageVisits: 'Zarządzanie wizytami',
  nextVisit: 'Następna wizyta beneficjenta',
  noResults: 'Brak wyników',
  organization: 'Organizacja',
  otherVisits: 'Inne',
  pickADay: 'Wybrana data: ',
  pickFile: 'Wybierz plik',
  pickEmployee: 'Wybierz terapeutę',
  plannedVisit: 'Zaplanowana wizyta',
  present: 'Obecny',
  selectDateRange: 'Wybierz zakres dat',
  selected: 'Zaznaczono:',
  status: 'Status',
  time: 'Godzina',
  addSheetForm: 'Formularz dodania harmonogramu pracy',
  employeesNotFound: 'Nie znaleziono pracowników',
  workScheduleHeader: 'Harmonogram pracownika',
  addSubstitution: 'Dodaj zastępstwo',
  noVisits: 'Brak wizyt dla podanej daty/godziny',
  addUserForm: 'Formularz dodania konta użytkownika',
  addEmployeeAbsenceForm: 'Formularz dodania nieobecności pracownika',
  loginForm: 'Formularz logowania',
  addCustomerAbsenceForm: 'Formularz dodania nieobecności beneficjenta',
  add: 'Dodaj',
  noAbsences: 'Brak nieobecności',
  employeeAbsences: 'Nieobecności pracowników',
  customerAbsences: 'Nieobecności beneficjentów',
  remove: 'Usuń',
  edit: 'Edytuj',
  save: 'Zapisz',
  viewVisits: 'Przejdź do wizyt',
  editDateRange: 'Edytuj zakres dat',
  filters: 'Filtry',
  search: 'Szukaj',
  noUsers: 'Brak użytkowników',
  username: 'Nazwa użytkownika',
  password: 'Hasło',
  roles: 'Role',
  resetPassword: 'Resetuj hasło',
  firstAndLastName: 'Imię i nazwisko',
  assignEmployee: 'Przypisz osobę',
  reportOptions: 'Kolumny',
  generate: 'Generuj',
  savedSheets: 'Zapisane harmonogramy pracy',
  savedReports: 'Zapisane raporty',
  noSheets: 'Brak zapisanych harmonogramów',
  noReports: 'Brak zapisanych raportów',
  login: 'Zaloguj',
  logo: 'Tęcza',
  employee: 'Pracownik'
};
